// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import BinanceServiceController from "./binance_service_controller"
import OrderController from "./order_controller"
import TradingViewChartController from "./trading_view_chart_controller"

application.register("hello", HelloController)
application.register("binance-service", BinanceServiceController)
application.register("order", OrderController)
application.register("trading-view-chart", TradingViewChartController)
